site_name: My Docs

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings
  - mike

nav:
  - Home: README.md
  - Tutorials:
      - tutorials/getting-started.md
  - How-To Guides:
      - how-to/dependencies.md
      - how-to/testing.md
      - how-to/docs.md
      - how-to/versioning.md
  - Explanation:
      - Aim of the Project: explanation/aim.md
      - Project Structure: explanation/structure.md
  - Reference:
      - Core:
          - Calculator: reference/core/calculator.md
      - CLI:
          - Calculator: reference/cli/calculator.md
