site_name: My Docs

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings
  - mike

nav:
  - Home: README.md
  - Tutorials:
      - Getting Started: tutorials/getting-started.md
  - How-To Guides:
      - Manage Dependencies: how-to/dependencies.md
      - Running tests: how-to/testing.md
      - Build Documentation: how-to/build-docs.md
  - Reference:
      - Core:
          - Calculator: reference/core/calculator.md
      - CLI:
          - Calculator: reference/cli/calculator.md
  - Explanation:
      - Project Structure: explanation/project-structure.md
      - Aim of the Project: explanation/aim-of-project.md
